# Generated by Django 4.2 on 2023-05-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.CharField(max_length=15)),
                ("name", models.CharField(max_length=30)),
                ("brith", models.DateField()),
                ("Depart", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="single_pages/images/%Y/%m/%d"
                    ),
                ),
            ],
        ),
    ]
