# Generated by Django 4.2 on 2023-05-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="content",
            new_name="contents",
        ),
    ]
