# Generated by Django 4.2 on 2023-04-24 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("single_pages", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="About",
            new_name="About_me",
        ),
    ]
