# Generated by Django 4.2 on 2023-04-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("single_pages", "0002_rename_about_about_me"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.CharField(max_length=15)),
                ("name", models.CharField(max_length=30)),
                ("brith", models.DateField()),
                ("Depart", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="About_me",
        ),
    ]
