# Generated by Django 4.2 on 2023-04-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("single_pages", "0003_student_delete_about_me"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="head_image",
            field=models.ImageField(blank=True, upload_to="reference/images/%Y/%m/%d"),
        ),
    ]
