# Generated by Django 4.2 on 2023-04-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("single_pages", "0004_student_head_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="head_image",
            field=models.ImageField(
                blank=True, upload_to="single_pages/images/%Y/%m/%d"
            ),
        ),
    ]
