# Generated by Django 4.2 on 2023-05-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("single_pages", "0006_rename_head_image_student_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
    ]
